owner: sudoblockio
repo: icon-status-page

sites:

  # GLOBAL MAINNET
  - name: Prod Mainnet Tracker Frontend
    url: https://tracker.icon.community/
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet API
    url: https://tracker.icon.community/api/v1/logs?method=Remove&limit=100&address=cxa0af3165c08318e988cb30993b3048335b94af6c
    headers:
      - "User-Agent: icon uptime"

#  - name: Prod Mainnet API
#    url: https://tracker.icon.community/api/v1/api/v1/blocks
#    headers:
#      - "User-Agent: icon uptime"

  - name: Prod Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/blocks

  - name: Prod Mainnet Governance Service
    url: https://tracker.icon.community/api/v1/governance/preps

  - name: Prod Mainnet Contracts Service
    url: https://tracker.icon.community/api/v1/contracts

  # Ams MAINNET
  - name: Prod Mainnet Tracker Frontend (Amsterdam)
    url: https://tracker.icon.community/

  - name: Prod Mainnet API (Amsterdam)
    url: https://tracker.icon.community/api/v1/blocks
  - name: Prod Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/blocks

  - name: Prod Mainnet Governance Service (Amsterdam)
    url: https://tracker.icon.community/api/v1/governance/preps
  - name: Prod Mainnet Contracts Service (Amsterdam)
    url: https://tracker.icon.community/api/v1/contracts

  # Sng MAINNET
  - name: Prod Mainnet Tracker Frontend (Singapore)
    url: https://tracker.icon.community/

  - name: Prod Mainnet API (Singapore)
    url: https://tracker.icon.community/api/v1/blocks
  - name: Prod Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/blocks

  - name: Prod Mainnet Governance Service (Singapore)
    url: https://tracker.icon.community/api/v1/governance/preps
  - name: Prod Mainnet Contracts Service (Singapore)
    url: https://tracker.icon.community/api/v1/contracts

  - name: Prod Mainnet RPC
    url: https://api.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Amsterdam RPC
    url: https://api.mainnet.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Singapore RPC
    url: https://api.mainnet.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Lisbon RPC
    url: https://api.lisbon.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Amsterdam RPC
    url: https://api.lisbon.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Singapore RPC
    url: https://api.lisbon.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Berlin RPC
    url: https://api.berlin.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
#  - name: Prod Berlin Amsterdam RPC
#    url: https://api.berlin.ams.vultr.icon.community/api/v3
#    method: POST
#    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Singapore RPC
    url: https://api.berlin.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'


status-website:
  links:
    - rel: stylesheet
      href: https://rheannone.github.io/CSS/css/icon-status_dark-theme.css
  cname: tracker.status.icon.community
  logoUrl: https://raw.githubusercontent.com/sudoblockio/icon-status-page/main/assets/icon-logo.png
  name: ICON Blockchain
  introTitle: |
    Status page for the **ICON Blockchain**
    Endpoints supported by **sudoblock**
  favicon: https://raw.githubusercontent.com/sudoblockio/icon-status-page/master/assets/icon-favicon.png
  metaTags:
    - name: "ICON Status"
    - content: "noIndex"
  introMessage: |

  navbar:
    - title: Status
      href: /
    - title: Grafana
      href: https://tracker.grafana.icon.community
    - title: GitHub
      href: https://github.com/$OWNER/icon-explorer

