owner: sudoblockio
repo: icon-status-page

sites:

  # GLOBAL MAINNET
  - name: Prod Mainnet Tracker Frontend
    url: https://tracker.icon.community/
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet API
    url: https://tracker.icon.community/api/v1/logs?method=Remove&limit=100&address=cxa0af3165c08318e988cb30993b3048335b94af6c
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/blocks

  - name: Prod Mainnet Governance Service
    url: https://tracker.icon.community/api/v1/governance/preps
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet Contracts Service
    url: https://tracker.icon.community/api/v1/contracts
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet Balanced
    url: https://balanced.icon.community/api/v1/tokens
    headers:
      - "User-Agent: icon uptime"

  - name: Prod Mainnet Balanced Cluster1
    url: https://cluster1.balanced.mainnet.icon.community/api/v1/tokens
    headers:
      - "User-Agent: icon uptime"

#  - name: Prod Mainnet Balanced Cluster2
#    url: https://cluster2.balanced.mainnet.icon.community/api/v1/tokens
#    headers:
#      - "User-Agent: icon uptime"

  - name: Prod Mainnet RPC
    url: https://api.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Cluster1 RPC
    url: https://cluster1.api.mainnet.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Cluster2 RPC
    url: https://cluster2.api.mainnet.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Singapore RPC
    url: https://api.mainnet.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Lisbon RPC
    url: https://api.lisbon.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Cluster1 RPC
    url: https://cluster1.api.lisbon.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Cluster2 RPC
    url: https://cluster2.api.lisbon.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Singapore RPC
    url: https://api.lisbon.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Berlin RPC
    url: https://api.berlin.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Cluster1 RPC
    url: https://cluster1.api.berlin.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Cluster2 RPC
    url: https://cluster2.api.berlin.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Singapore RPC
    url: https://api.berlin.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'


status-website:
  links:
    - rel: stylesheet
      href: https://rheannone.github.io/CSS/css/icon-status_dark-theme.css
  cname: tracker.status.icon.community
  logoUrl: https://raw.githubusercontent.com/sudoblockio/icon-status-page/main/assets/icon-logo.png
  name: ICON Blockchain
  introTitle: |
    Status page for the **ICON Blockchain**
    Endpoints supported by **sudoblock**
  favicon: https://raw.githubusercontent.com/sudoblockio/icon-status-page/master/assets/icon-favicon.png
  metaTags:
    - name: "ICON Status"
    - content: "noIndex"
  introMessage: |

  navbar:
    - title: Status
      href: /
    - title: Grafana
      href: https://tracker.grafana.icon.community
    - title: GitHub
      href: https://github.com/$OWNER/icon-explorer

